settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 3000
  host: localhost
schema:
- name: go-pricing
  path: .
  args:
    - pricing.go
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
